plugin.yaml
plugin/gcp/service.py
plugin/gcp/utils.py
plugin/integration_tests/test_plugin.py
plugin/integration_tests/test_service.py
plugin/tasks.py
plugin/tests/test_utils.py

Added docstrings to plugin.gcp.utils.
Created function to generate resource name compliant with GCP.

Resource name transformation

---

plugin.yaml
plugin/gcp/service.py
plugin/integration_tests/test_plugin.py
plugin/integration_tests/test_service.py
plugin/tasks.py
scripts/bootstrap_manager.py
scripts/startup-script.sh

Add upload auth file during bootstrap

Bootstrap upload auth file

---

cloudify_gcp/compute/address.py
cloudify_gcp/compute/disk.py
cloudify_gcp/compute/firewall.py
cloudify_gcp/compute/forwarding_rule.py
cloudify_gcp/compute/image.py
cloudify_gcp/compute/instance.py
cloudify_gcp/compute/instance_group.py
cloudify_gcp/compute/network.py
cloudify_gcp/compute/ssl_certificate.py
cloudify_gcp/compute/target_proxy.py
cloudify_gcp/compute/tests/test_address.py
cloudify_gcp/compute/tests/test_disk.py
cloudify_gcp/compute/tests/test_firewall.py
cloudify_gcp/compute/tests/test_forwarding_rule.py
cloudify_gcp/compute/tests/test_image.py
cloudify_gcp/compute/tests/test_instance_group.py
cloudify_gcp/compute/tests/test_network.py
cloudify_gcp/compute/tests/test_target_proxy.py
cloudify_gcp/compute/tests/test_url_map.py
cloudify_gcp/compute/url_map.py
cloudify_gcp/dns/dns.py
cloudify_gcp/dns/tests/test_dns.py
cloudify_gcp/gcp.py
plugin.yaml

GCP-13 additional settings

---

cloudify_gcp/compute/instance.py
cloudify_gcp/compute/tests/test_instance.py
cloudify_gcp/constants.py
cloudify_gcp/tests/__init__.py
cloudify_gcp/tests/test_utils.py
cloudify_gcp/utils.py

Gcp 14 remove provider context

---

cloudify_gcp/compute/instance.py
cloudify_gcp/compute/tests/test_instance.py
local-storage/local/resources/external-ip-blueprint.yaml
plugin.yaml
system_tests/local/__init__.py
system_tests/local/test_instance.py
system_tests/resources/compute/external-ip-property-blueprint.yaml

Gcp 15 external ip property fix

---

cloudify_gcp/compute/forwarding_rule.py
cloudify_gcp/compute/security_group.py
cloudify_gcp/compute/subnetwork.py
cloudify_gcp/compute/target_proxy.py
cloudify_gcp/compute/tests/test_subnetwork.py
cloudify_gcp/compute/url_map.py
cloudify_gcp/dns/record.py
cloudify_gcp/utils.py

Gcp 16 operations not registered

---

cloudify_gcp/compute/instance_group.py
cloudify_gcp/compute/tests/test_backend_service.py
cloudify_gcp/compute/tests/test_instance.py
cloudify_gcp/compute/tests/test_instance_group.py
cloudify_gcp/compute/tests/test_network.py
cloudify_gcp/compute/tests/test_route.py
cloudify_gcp/compute/tests/test_subnetwork.py
cloudify_gcp/utils.py
plugin.yaml
system_tests/local/test_http_forwarding.py
system_tests/local/test_https_forwarding.py
system_tests/local/test_instance_group.py
system_tests/resources/compute/instance-group-blueprint.yaml
system_tests/resources/http_forwarding/global-https-static-ip-blueprint.yaml
system_tests/resources/http_forwarding/global-static-ip-blueprint.yaml

More reliable:
using utils.async_operation to retry until the Operation is done
using the Instance's URL (selfLink)
JIRA: GCP-17

GCP-17 instance_connected_to_instance_group improvements

---

cloudify_gcp/compute/tests/test_firewall.py
cloudify_gcp/compute/tests/test_instance.py
cloudify_gcp/compute/tests/test_route.py
cloudify_gcp/compute/tests/test_security_group.py
cloudify_gcp/tests/test_utils.py
cloudify_gcp/utils.py

Gcp 18 allow short network name

---

cloudify_gcp/compute/instance_group.py
cloudify_gcp/compute/tests/test_instance_group.py
cloudify_gcp/tests/test_utils.py
cloudify_gcp/utils.py

(it's unreliable on 3.3.1 and unnecessary on 3.4)
JIRA: GCP-23

GCP-23 Don't use async_operation for relationship operations

---

cloudify_gcp/compute/route.py
cloudify_gcp/compute/tests/test_route.py
cloudify_gcp/compute/tests/test_subnetwork.py
cloudify_gcp/dns/tests/test_record.py
cloudify_gcp/utils.py
system_tests/local/test_route.py
system_tests/resources/route/simple-blueprint.yaml

GCP-21 Add get_resources_type and look for it in get_relationships

---

cloudify_gcp/compute/instance.py
cloudify_gcp/compute/tests/test_instance.py
system_tests/local/test_2_subnetworks.py
system_tests/resources/networks/external-networks-blueprint.yaml
system_tests/resources/networks/simple-blueprint.yaml

JIRA: GCP-27
Like GCP-25 this overlaps with previous PRs so isn't ready to merge yet
(one of the tests that needed updating for this change was introduced in a not-yet-merged PR)

Gcp 27 dont guess zones

---

cloudify_gcp/compute/instance.py
cloudify_gcp/compute/tests/test_instance.py
system_tests/local/__init__.py
system_tests/local/test_instance.py
system_tests/local/test_route.py
system_tests/local/test_static_ip.py
system_tests/resources/keypair/simple-blueprint.yaml

Gcp 28 ip attribute always internal

---

cloudify_gcp/compute/instance.py
cloudify_gcp/compute/tests/test_instance.py

Gcp 29 disk rel operations sync decorator

---

cloudify_gcp/tests/test_utils.py
cloudify_gcp/utils.py
plugin.yaml

GCP-33 NonRecoverableError if ssh key generation fails

---

cloudify_gcp/compute/backend_service.py
cloudify_gcp/compute/health_check.py
cloudify_gcp/compute/target_proxy.py
cloudify_gcp/compute/tests/test_backend_service.py
cloudify_gcp/compute/tests/test_health_check.py
cloudify_gcp/compute/tests/test_target_proxy.py
plugin.yaml

various types of load balancers.

Update BackendService, HealthCheck and TargetProxy nodes for support

---

CHANGELOG.txt
cloudify_gcp/compute/firewall.py
cloudify_gcp/compute/keypair.py
cloudify_gcp/compute/network.py
cloudify_gcp/compute/tests/test_instance.py
cloudify_gcp/compute/tests/test_keypair.py
cloudify_gcp/container_engine/legacy_abac.py
cloudify_gcp/container_engine/monitoring.py
cloudify_gcp/container_engine/network_policy.py
cloudify_gcp/pubsub/acknowledge.py
cloudify_gcp/pubsub/message.py
cloudify_gcp/pubsub/pull_request.py
cloudify_gcp/pubsub/subscription_policy.py
cloudify_gcp/pubsub/topic_policy.py
cloudify_gcp/tests/test_utils.py
cloudify_gcp/utils.py
plugin.yaml
setup.py

Fix for:
https://github.com/cloudify-cosmo/cloudify-gcp-plugin/issues/85

Gcp 85 include resource id in gcp nodes

---

cloudify_gcp/constants.py
cloudify_gcp/logging/__init__.py
cloudify_gcp/logging/exclusion.py
cloudify_gcp/logging/project_metrics.py
cloudify_gcp/logging/sink.py
cloudify_gcp/logging/tests/test_exclusions.py
cloudify_gcp/logging/tests/test_project_metric.py
cloudify_gcp/logging/tests/test_sink.py
plugin.yaml
setup.py
system_tests/resources/logging/sample-blueprint.yaml

Loggin phase I from
https://github.com/cloudify-cosmo/cloudify-gcp-plugin/issues/62

support logging components for GCP

---

.circleci/config.yml
.circleci/test_examples.py
CHANGELOG.txt
plugin.yaml
setup.py
test-requirements.txt

Replace wagon builder to py2py3 builder

---

CHANGELOG.txt
dev-requirements.txt
plugin.yaml
setup.py

RD-1611 Replace pycrypto 2.6.1 with pycryptodome 3.9.8

---

.circleci/config.yml

rename wagon builds

---

CHANGELOG.txt
cloudify_gcp/compute/disk.py
cloudify_gcp/compute/tests/test_disk.py
plugin.yaml
plugin_1_4.yaml
v2_plugin.yaml

* resize disk feature ready
* disk resize test WIP
Co-authored-by: Jakub Cierlik <jakub.cierlik@amartus.com>

Volume resize (#197)

---

.circleci/config.yml

* update setup manager urllib3==1.26.15 (#218)
* update to plugin_1_5.yaml

NE-10723-fix-circleci-config (#220)
